.base: &base
  forwardAgent: true
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  deploy_path: /var/data/secure # ここに案件のdeployパスを記入

test:
  <<: *base
  hostname: secure.local
  local: true
  stage: test

# stagging:
#   <<: *base
#   hostname: trs.bastion
#   local: true
#   stage: stagging

# product-web1:
#   <<: *base
#   hostname: web1
#   stage: production

# product-web2:
#   <<: *base
#   hostname: web2
#   stage: production
